kind: Service
apiVersion: v1
metadata:
  name: rocketchat-server-service
  namespace: rocketchat

spec:
  selector:
    app: rocketchat-server
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: LoadBalancer
