kind: Service
apiVersion: v1
metadata:
  name: rocketchat-mongo-service
  namespace: rocketchat
spec:
  selector:
    app: rocketchatmongo
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
